"""Add document_url to Article

Revision ID: c877000de829
Revises: 09d6266dba28
Create Date: 2025-09-28 12:50:43.125859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c877000de829'
down_revision = '09d6266dba28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('document_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'document_url')
    # ### end Alembic commands ###
