"""Remove document_url from Article

Revision ID: e3962e2708c4
Revises: c877000de829
Create Date: 2025-09-28 12:56:07.512982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3962e2708c4'
down_revision = 'c877000de829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'document_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('document_url', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
